version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres_container
    environment:
      - DEBUG=1  # Set to 0 in production
      - DJANGO_DB_HOST=postgres_container
      - DJANGO_DB_NAME=bus_maintenance  # Changed to match PostgreSQL database name
      - DJANGO_DB_USER=abu  # Changed to match PostgreSQL username
      - DJANGO_DB_PASSWORD=1234  # Changed to match PostgreSQL password
      - DJANGO_DB_PORT=5432
  
  postgres_container:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bus_maintenance
      - POSTGRES_USER=abu
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres_container
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin

volumes:
  postgres_data:
