# Generated by Django 3.2.16 on 2023-09-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaintenanceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FORECAST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VEH_ID', models.CharField(max_length=255)),
                ('forecast_dt', models.DateTimeField()),
                ('SPN_110_fc', models.FloatField()),
                ('SPN_110_fc_lower', models.FloatField()),
                ('SPN_110_fc_upper', models.FloatField()),
                ('SPN_183_fc', models.FloatField()),
                ('SPN_183_fc_lower', models.FloatField()),
                ('SPN_183_fc_upper', models.FloatField()),
                ('SPN_184_fc', models.FloatField()),
                ('SPN_184_fc_lower', models.FloatField()),
                ('SPN_184_fc_upper', models.FloatField()),
                ('SPN_84_fc', models.FloatField()),
                ('SPN_84_fc_lower', models.FloatField()),
                ('SPN_84_fc_upper', models.FloatField()),
                ('SPN_190_fc', models.FloatField()),
                ('SPN_190_fc_lower', models.FloatField()),
                ('SPN_190_fc_upper', models.FloatField()),
                ('SPN_96_fc', models.FloatField()),
                ('SPN_96_fc_lower', models.FloatField()),
                ('SPN_96_fc_upper', models.FloatField()),
                ('SPN_91_fc', models.FloatField()),
                ('SPN_91_fc_lower', models.FloatField()),
                ('SPN_91_fc_upper', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PROCESSED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPOT_ID', models.CharField(max_length=255)),
                ('DEPOT_NM', models.CharField(max_length=255)),
                ('MODEL_NUM', models.CharField(max_length=255)),
                ('SPN_1821', models.CharField(max_length=255)),
                ('SPN_597', models.CharField(max_length=255)),
                ('VEH_ID', models.CharField(max_length=255)),
                ('EVT_DATETIME', models.DateTimeField()),
                ('SPN_513', models.FloatField()),
                ('SPN_190', models.FloatField()),
                ('SPN_91', models.FloatField()),
                ('SPN_92', models.FloatField()),
                ('SPN_524', models.FloatField()),
                ('SPN_523', models.FloatField()),
                ('SPN_1087', models.FloatField()),
                ('SPN_1088', models.FloatField()),
                ('SPN_917', models.FloatField()),
                ('SPN_247', models.FloatField()),
                ('SPN_250', models.FloatField()),
                ('SPN_110', models.FloatField()),
                ('SPN_84', models.FloatField()),
                ('SPN_183', models.FloatField()),
                ('SPN_184', models.FloatField()),
                ('SPN_171', models.FloatField()),
                ('SPN_96', models.FloatField()),
                ('month', models.IntegerField()),
                ('dayofmonth', models.IntegerField()),
                ('dayofweek', models.IntegerField()),
                ('hourofday', models.IntegerField()),
                ('weekday', models.BooleanField()),
                ('ops_hours', models.BooleanField()),
            ],
        ),
    ]
