# Generated by Django 3.2.16 on 2023-09-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaintenanceApp', '0002_forecast_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=50, unique=True)),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
            ],
        ),
    ]
